services:
  shared_rust:
    build: ./shared_rust
    image: shared-rust
  server:
    depends_on:
      - shared_rust
    build: ./server
    volumes:
      - ./public:/app/public
    ports:
      - 8080:3000
