services:

  shared-rust:
    build: ./shared-rust
    image: shared-rust

  server:
    depends_on:
      - shared-rust
    build: ./server
    networks:
      - algonet
      - grafnet
    ports:
      - 8080:3000
    volumes:
      - ./public:/app/public

  algonet-client:
    depends_on:
      - server
    build: ./algorithm-base
    image: algonet-client

  algorithm-foo1:
    depends_on:
      - algonet-client
    build: ./algorithms/foo1
    networks:
      - algonet
    
  algorithm-foo2:
    depends_on:
      - algonet-client
    build: ./algorithms/foo2
    networks:
      - algonet

  algorithm-greedy:
    depends_on:
      - algonet-client
    build: ./algorithms/greedy
    networks:
      - algonet
    cap_add:
      - SYS_ADMIN
    volumes:
      - /sys/kernel/debug:/sys/kernel/debug
  
  graph-generator:
    build: ./graph-generation
    image: graph-generator
    environment:
      - JVM_ARGS=-Xms256M -Xmx512M
    networks:
      - grafnet

networks:
  algonet:
  grafnet:
