[package]
name = "algorithm-base"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../shared-rust" }
bincode = "1.3"
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.24"
